/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthLayoutRouteImport } from './routes/auth/_layout'
import { Route as AppLayoutRouteImport } from './routes/app/_layout'
import { Route as AuthLayoutSignupRouteImport } from './routes/auth/_layout/signup'
import { Route as AuthLayoutOtpRouteImport } from './routes/auth/_layout/otp'
import { Route as AuthLayoutLoginRouteImport } from './routes/auth/_layout/login'
import { Route as AuthLayoutForgetPasswordRouteImport } from './routes/auth/_layout/forgetPassword'
import { Route as AppLayoutTicketsIndexRouteImport } from './routes/app/_layout/tickets/index'
import { Route as AppLayoutTechniciansIndexRouteImport } from './routes/app/_layout/technicians/index'
import { Route as AppLayoutAccountIndexRouteImport } from './routes/app/_layout/account/index'
import { Route as AuthLayoutResetPasswordResetLinkRouteImport } from './routes/auth/_layout/resetPassword.$resetLink'
import { Route as AppLayoutTicketsTicketIdRouteImport } from './routes/app/_layout/tickets/$ticketId'

const AuthRouteImport = createFileRoute('/auth')()
const AppRouteImport = createFileRoute('/app')()

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AppRoute,
} as any)
const AuthLayoutSignupRoute = AuthLayoutSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutOtpRoute = AuthLayoutOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutLoginRoute = AuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutForgetPasswordRoute =
  AuthLayoutForgetPasswordRouteImport.update({
    id: '/forgetPassword',
    path: '/forgetPassword',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AppLayoutTicketsIndexRoute = AppLayoutTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutTechniciansIndexRoute =
  AppLayoutTechniciansIndexRouteImport.update({
    id: '/technicians/',
    path: '/technicians/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutAccountIndexRoute = AppLayoutAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthLayoutResetPasswordResetLinkRoute =
  AuthLayoutResetPasswordResetLinkRouteImport.update({
    id: '/resetPassword/$resetLink',
    path: '/resetPassword/$resetLink',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AppLayoutTicketsTicketIdRoute =
  AppLayoutTicketsTicketIdRouteImport.update({
    id: '/tickets/$ticketId',
    path: '/tickets/$ticketId',
    getParentRoute: () => AppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/auth/forgetPassword': typeof AuthLayoutForgetPasswordRoute
  '/auth/login': typeof AuthLayoutLoginRoute
  '/auth/otp': typeof AuthLayoutOtpRoute
  '/auth/signup': typeof AuthLayoutSignupRoute
  '/app/tickets/$ticketId': typeof AppLayoutTicketsTicketIdRoute
  '/auth/resetPassword/$resetLink': typeof AuthLayoutResetPasswordResetLinkRoute
  '/app/account': typeof AppLayoutAccountIndexRoute
  '/app/technicians': typeof AppLayoutTechniciansIndexRoute
  '/app/tickets': typeof AppLayoutTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppIndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/auth/forgetPassword': typeof AuthLayoutForgetPasswordRoute
  '/auth/login': typeof AuthLayoutLoginRoute
  '/auth/otp': typeof AuthLayoutOtpRoute
  '/auth/signup': typeof AuthLayoutSignupRoute
  '/app/tickets/$ticketId': typeof AppLayoutTicketsTicketIdRoute
  '/auth/resetPassword/$resetLink': typeof AuthLayoutResetPasswordResetLinkRoute
  '/app/account': typeof AppLayoutAccountIndexRoute
  '/app/technicians': typeof AppLayoutTechniciansIndexRoute
  '/app/tickets': typeof AppLayoutTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/_layout': typeof AppLayoutRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/_layout': typeof AuthLayoutRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/auth/_layout/forgetPassword': typeof AuthLayoutForgetPasswordRoute
  '/auth/_layout/login': typeof AuthLayoutLoginRoute
  '/auth/_layout/otp': typeof AuthLayoutOtpRoute
  '/auth/_layout/signup': typeof AuthLayoutSignupRoute
  '/app/_layout/tickets/$ticketId': typeof AppLayoutTicketsTicketIdRoute
  '/auth/_layout/resetPassword/$resetLink': typeof AuthLayoutResetPasswordResetLinkRoute
  '/app/_layout/account/': typeof AppLayoutAccountIndexRoute
  '/app/_layout/technicians/': typeof AppLayoutTechniciansIndexRoute
  '/app/_layout/tickets/': typeof AppLayoutTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/'
    | '/auth/forgetPassword'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/signup'
    | '/app/tickets/$ticketId'
    | '/auth/resetPassword/$resetLink'
    | '/app/account'
    | '/app/technicians'
    | '/app/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/auth/forgetPassword'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/signup'
    | '/app/tickets/$ticketId'
    | '/auth/resetPassword/$resetLink'
    | '/app/account'
    | '/app/technicians'
    | '/app/tickets'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/_layout'
    | '/auth'
    | '/auth/_layout'
    | '/app/'
    | '/auth/_layout/forgetPassword'
    | '/auth/_layout/login'
    | '/auth/_layout/otp'
    | '/auth/_layout/signup'
    | '/app/_layout/tickets/$ticketId'
    | '/auth/_layout/resetPassword/$resetLink'
    | '/app/_layout/account/'
    | '/app/_layout/technicians/'
    | '/app/_layout/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/_layout': {
      id: '/app/_layout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/_layout/signup': {
      id: '/auth/_layout/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthLayoutSignupRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/_layout/otp': {
      id: '/auth/_layout/otp'
      path: '/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthLayoutOtpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/_layout/login': {
      id: '/auth/_layout/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLayoutLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/_layout/forgetPassword': {
      id: '/auth/_layout/forgetPassword'
      path: '/forgetPassword'
      fullPath: '/auth/forgetPassword'
      preLoaderRoute: typeof AuthLayoutForgetPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/app/_layout/tickets/': {
      id: '/app/_layout/tickets/'
      path: '/tickets'
      fullPath: '/app/tickets'
      preLoaderRoute: typeof AppLayoutTicketsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/technicians/': {
      id: '/app/_layout/technicians/'
      path: '/technicians'
      fullPath: '/app/technicians'
      preLoaderRoute: typeof AppLayoutTechniciansIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/account/': {
      id: '/app/_layout/account/'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppLayoutAccountIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/auth/_layout/resetPassword/$resetLink': {
      id: '/auth/_layout/resetPassword/$resetLink'
      path: '/resetPassword/$resetLink'
      fullPath: '/auth/resetPassword/$resetLink'
      preLoaderRoute: typeof AuthLayoutResetPasswordResetLinkRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/app/_layout/tickets/$ticketId': {
      id: '/app/_layout/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/app/tickets/$ticketId'
      preLoaderRoute: typeof AppLayoutTicketsTicketIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppLayoutTicketsTicketIdRoute: typeof AppLayoutTicketsTicketIdRoute
  AppLayoutAccountIndexRoute: typeof AppLayoutAccountIndexRoute
  AppLayoutTechniciansIndexRoute: typeof AppLayoutTechniciansIndexRoute
  AppLayoutTicketsIndexRoute: typeof AppLayoutTicketsIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutTicketsTicketIdRoute: AppLayoutTicketsTicketIdRoute,
  AppLayoutAccountIndexRoute: AppLayoutAccountIndexRoute,
  AppLayoutTechniciansIndexRoute: AppLayoutTechniciansIndexRoute,
  AppLayoutTicketsIndexRoute: AppLayoutTicketsIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AppRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthLayoutRouteChildren {
  AuthLayoutForgetPasswordRoute: typeof AuthLayoutForgetPasswordRoute
  AuthLayoutLoginRoute: typeof AuthLayoutLoginRoute
  AuthLayoutOtpRoute: typeof AuthLayoutOtpRoute
  AuthLayoutSignupRoute: typeof AuthLayoutSignupRoute
  AuthLayoutResetPasswordResetLinkRoute: typeof AuthLayoutResetPasswordResetLinkRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutForgetPasswordRoute: AuthLayoutForgetPasswordRoute,
  AuthLayoutLoginRoute: AuthLayoutLoginRoute,
  AuthLayoutOtpRoute: AuthLayoutOtpRoute,
  AuthLayoutSignupRoute: AuthLayoutSignupRoute,
  AuthLayoutResetPasswordResetLinkRoute: AuthLayoutResetPasswordResetLinkRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
